version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_network
  kafka:
    image: bitnami/kafka:3.9.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app_network
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=teste
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - app_network
  mysql:
    image: mysql:8.0.25
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: teste-kafka
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --lower-case-table-names=0 --max_allowed_packet=100M
    networks:
      - app_network
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 7070:8080
    networks:
      - app_network
  producer:
    image: marceloagmelo/java-kafka-producer:2.0.0.RELEASE
    platform: linux/amd64
    build:
      context: ../java-kafka-producer
      dockerfile: Dockerfile
    container_name: producer
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: teste-kafka
      MYSQL_USER: root
      MYSQL_PASS: 12345
      KAFKA_SERVER: kafka:9092
    depends_on:
      - mysql
      - kafka
    networks:
      - app_network
  consumer:
    image: marceloagmelo/java-kafka-consumer:1.0.0.RELEASE
    platform: linux/amd64
    build:
      context: ../java-kafka-consumer
      dockerfile: Dockerfile
    container_name: consumer
    restart: always
    environment:
      KAFKA_SERVER: kafka:9092
      PRODUCER_ENDPOINT: http://producer:8080/clientes
    depends_on:
      - producer
    networks:
      - app_network
networks:
  app_network:
    name: app_network
