apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
